name: ci/cd-pipeline

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with .NET
        run: |
          cd WebAPI
          dotnet build --configuration Release
      
      - name: Publish .NET
        run: |
          cd WebAPI
          dotnet publish -c Release -o published

      - name: Copy dotnet to IIS
        run: |
          Copy-Item -Path "$env:GITHUB_WORKSPACE\*" -Destination "C:\www\webapi_app" -Recurse -Force
          
                
