name: ci/cd-pipeline

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with .NET
        run: |
          cd WebAPI
          dotnet build --configuration Release
      
      - name: Publish .NET
        run: |
          dotnet publish -c Release -o .\myapp
          
                
